// Generated by CoffeeScript 1.6.2
(function() {
  define([], function() {
    _events;
    var returnedObject;

    return returnedObject = {
      Events: _events
    };
  });

  this.sliderEvents = [];

  $(document).ready(function() {
    return $('#mainSlider').find('#sliderButtons').find('.Button').each(function(index) {
      return $(this).click(function() {
        var corespondingItem, pressedLink;

        pressedLink = $(this);
        corespondingItem = $('#item-' + pressedLink.attr("number"));
        console.log("pressed link = " + pressedLink.attr("number"));
        console.log("responding item = " + '#item-' + pressedLink.attr("number"));
        if (pressedLink.attr("active") === "true") {
          return $('#mainSlider').find('#sliderButtons').find('.Button ').removeClass("selected");
        } else {
          console.log("event");
          sliderEvents[index]();
          pressedLink.attr("active", "true");
          return pressedLink.addClass("selected");
        }
      });
    });
  });

  sliderEvents.push(function() {
    var corespondingItem;

    hideVisableSlide();
    corespondingItem = $('#item-0');
    return corespondingItem.addClass("selected");
  });

  sliderEvents.push(function() {
    var corespondingItem;

    hideVisableSlide();
    corespondingItem = $('#item-1');
    return corespondingItem.addClass("selected");
  });

  sliderEvents.push(function() {
    var corespondingItem;

    hideVisableSlide();
    corespondingItem = $('#item-2');
    return corespondingItem.addClass("selected");
  });

  sliderEvents.push(function() {
    var corespondingItem;

    hideVisableSlide();
    corespondingItem = $('#item-3');
    return corespondingItem.addClass("selected");
  });

  this.hideVisableSlide = function() {
    $('.itemContainer').removeClass("selected");
    $('#mainSlider').find('#sliderButtons').find('.Button ').removeClass("selected");
    return $('#mainSlider').find('#sliderButtons').find('.Button ').attr("active", "false");
  };

}).call(this);
